### ISSUE TITLE
EDM ZynAddSubFX presets

### ISSUE THREAD

**Issue by SimoneIervasi** [LMMS/samples#19]
Hi! I'm designing with 5 other musicians some high quality EDM presets for ZynAddSubFX. Would you been interested in this? 
Simone

**Comment by Umcaruje** [comment]
Hi simone, we get our ZynAddSubFX presets from the upstream, so you'll need to contact the zyn dev team about adding your presets to ZynAddSubFX. Once they get added upstream, they will be pulled downstream to LMMS.
Some useful info:
The current zyn mantainer is @fundamental, he will probably help you with that.

You can also post to the zyn user list: https://lists.sourceforge.net/lists/listinfo/zynaddsubfx-user which seems like a suitable place for this kind of thing.

Anyways, I'm gonna close this now, since this is really an upstream issue and not ours.

**Comment by tresf** [comment]
> Hi simone, we get our ZynAddSubFX presets from the upstream, so you'll need to contact the zyn dev team about adding your presets to ZynAddSubFX. Once they get added upstream, they will be pulled downstream to LMMS.

@fundamental do you agree with this approach?  Would upstream be best for Preset Additions?

I'm the one that sent @SimoneIervasi here, as I thought this would be an appropriate place for conversation and collaboration.

**Comment by fundamental** [comment]
@tresf I'd say the mailing list would likely be the right place. To quote the old README in zyn's repo:

```
    --==## PLEASE SHARE YOUR INSTRUMENTS/MASTER SETTINGS ##==--
              --==## MADE WITH ZynAddSubFX ##==--
    Here is the mailing list where you can share your patches with others:
      http://lists.sourceforge.net/mailman/listinfo/zynaddsubfx-user
```

Generally if there's enough good quality patches and they don't overlap with existing ones they would be added via a new bank in the instruments repository:
https://sourceforge.net/p/zynaddsubfx/instruments/ci/master/tree/

If this is getting discussed on the zynaddsubfx mailing list then I'd expect the patches to run with only zynaddsubfx and not require any external effects or automation to sound 'right'.

**Comment by tresf** [comment]
> If this is getting discussed on the zynaddsubfx mailing list then I'd expect the patches to run with only zynaddsubfx and not require any external effects or automation to sound 'right'.

Good point.  I'll let @SimoneIervasi chime in on whether or not he's stacked some non-Zyn effects on top of these or not.  If he has, we're his only home.  If he hasn't, it sounds like the Zyn mailing list is the place to discuss. :+1:

**Comment by Umcaruje** [comment]
> I'll let @SimoneIervasi chime in on whether or not he's stacked some non-Zyn effects on top of these or not. If he has, we're his only home. If he hasn't, it sounds like the Zyn mailing list is the place to discuss. :+1:

Yeah, that sounds reasonable. I'll reopen the issue if the presets turn out to be LMMS only. :+1:

**Comment by SimoneIervasi** [comment]
I have used some LMMS effects (Reverb, Stereo Enhancer ecc.), but if you want i'll try to use only ZynAddSubFX👍
