### ISSUE TITLE
New Sample guidelines

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/samples#20]
Hello, SirBothersome here, I'm now taking charge of the LMMS samples repo. Before we get started here I think we should establish a few conventions for posting new samples.
Samples should be:
a) Made by you. At this point, if we're going to get this done in a timely manner, we should avoid using third-party samples. The process of contacting the owners, licensing, and clearing the samples is going to be a time drain. So let's skip that for now.
b) Functional. I'm essentially starting from scratch here. We need the basics, Acoustic drums, techno drums, some 808's _and that's it for the moment_ niche samples like beatboxing or death metal screams are just going to clog the review process as of now
c) Varied. By which I mean, let's not just have 80 siney techno kicks and dubstep snares for our techno pack. We don't have to provide a full-spectrum key-labeled Kickdrum array. Just the essentials.
and d) Useful. This sample selection should be for producers, by producers, so please be sure that samples have minimal predelay, background noise and are eq'd/compressed for plug and play use.
Sorry if I'm bossy, but that's what I think we need to do.
God Bless and good day

**Comment by Umcaruje** [comment]
>The process of contacting the owners, licensing, and clearing the samples is going to be a time drain.

You do realise this is something that's scheduled for a version of LMMS after 1.2 (which is not even released yet), so I don't think time is really an issue. The problem I see here is that you never mentioned the importance of the quality of the samples. I think having high quality is very important and if this new sample pack is just there to replace the current samples with a similar quality but CC0 samples, it'd be the wrong approach. 

So I disagree on accepting only self-made samples by people from the community, and disregarding something where some work was already done. Markus Hakala's kicks are something truly amazing and it would be sad if they weren't added to the new sample pack.

> I'm now taking charge of the LMMS samples repo. 

I won't add you to the sample editors team, which means you can work on this, but only from your fork, and the samples you provide will need to be reviewed prior to merging. That said, all help is appreciated and I wish you luck on this.

**Comment by tresf** [comment]
Also, the guidelines themselves belong in a formatted wiki, not a bug tracker.  You can us this bug (#20) for now to discuss and agree up on guidelines, but the guidelines themselves should be placed in a document, not an issue thread and this issue should be closed.

Part of managing a team of contributors as well as a source repository is getting to know how the process works, hence reactions like this:

> I won't add you to the sample editors team, which means you can work on this, but only from your fork, and the samples you provide will need to be reviewed prior to merging. 

:+1:

**Comment by tresf** [comment]
@SirBothersome find another place to be bothersome, please.

**Comment by SirBothersome** [comment]
> @SirBothersome find another place to be bothersome, please.

Fair enough. How's about I disappear for a week and come back with some shiny new samples?
 I doubt I'll be missed.
God Bless and good day
