### ISSUE TITLE
New Sample Collesium

### ISSUE THREAD

**Issue by SirBothersome** [LMMS/samples#21]
This is where I'll be posting the new samples in batches. If you like it, YAY. I'll fast-track it to the repo for the pull request. If you don't like it... BLEARGH!!! It's bloodily dismembered and probably reprocessed or maybe Shift+deleted into oblivion.  If you don't like something, don't hesitate to tell me why... I don't think I should be the only voice in my head.

**Comment by tresf** [comment]
Let's use Pull Requests please.

**Comment by Umcaruje** [comment]
>If you don't like it... BLEARGH!!! It's bloodily dismembered and probably reprocessed or maybe Shift+deleted into oblivion

... what

**Comment by SirBothersome** [comment]
> Let's use Pull Requests please.

@tresf, You yourself were critiquing the quality of my samples sir. I'll happily compile a new library, but I'm trying to do this so the process is democratic and the pull request(s) is not just a big fat NO. The way I use samples might be different from how you or @Umcaruje uses them. This allows me to find some common ground for the greatest functionality

**Comment by SirBothersome** [comment]
> ... what

The sample you didn't like @Umcaruje. Supposing you listened to it. I understand that too many cooks spoil the soup, but having only one cook may result in chicken beak and gravy stew that only hipsters like.
